version: '3.9'

services:
  mysqldb:
    container_name: db
    image: mariadb:10.7
    env_file:
      - environment/dev/mysql.env
    environment:
      - MYSQL_ROOT_PASSWORD=lSj58osiU12kjdj43shaSDDz
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  symfony:
    container_name: symfony
    image: fguntz/symfony:2.0
    env_file:
      - environment/dev/symfony.env
    volumes:
      - ./symfony/php-dev.ini:/usr/local/etc/php/php.ini:ro
      - ./symfony/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ../api:/var/www/app
      - api-vendor:/var/www/app/vendor
    working_dir: /var/www/app
    restart: always
    command: bash -c "composer install && php-fpm"

  http:
    container_name: api
    image: nginx:1.21.6-alpine
    depends_on:
      - symfony
    volumes:
      - ../api:/var/www/app:ro
      - ./http/server-dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 127.0.0.1:8080:80
    restart: always
    tty: true

  npm:
    container_name: www_wys
    image: node:17
    env_file:
      - environment/dev/npm.env
    volumes:
      - ../app:/var/www/app
      - nodemodules:/src/node_modules
    working_dir: /var/www/app
    ports:
      - 127.0.0.1:3000:3000
    restart: always
    command: bash -c "npm cache clear -f && npm install -f && npm run serve"
    tty: true

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.1
    env_file:
      - environment/dev/phpmyadmin.env
    volumes:
      - /sessions
    ports:
      - 127.0.0.1:8888:80
    restart: always

volumes:
  nodemodules: {}
  api-vendor:
  mysql-data:
  mongo-data:
